name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  bloom:
    name: Bloom - Build
    runs-on: macos-latest

    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_13.2.app/Contents/Developer

      - name: Build
        run: xcodebuild clean build -workspace swiftui-challenge.xcworkspace  -scheme "Bloom" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 13"
  
  mysoothe:
    name: MySoothe - Build
    runs-on: macos-latest

    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_13.2.app/Contents/Developer

      - name: Build
        run: xcodebuild clean build -workspace swiftui-challenge.xcworkspace  -scheme "MySoothe" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 13"

  wetrade:
    name: WeTrade - Build
    runs-on: macos-latest

    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_13.2.app/Contents/Developer

      - name: Build
        run: xcodebuild clean build -workspace swiftui-challenge.xcworkspace  -scheme "WeTrade" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 13"